# Generated by Django 4.1.7 on 2023-03-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(default='', max_length=250)),
                ('image', models.ImageField(upload_to='user-images')),
                ('link', models.URLField()),
                ('publish_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
    ]
